services:
  app:
    build:
      context: ./app
    restart: unless-stopped
    env_file:
      - ./.env.local
    ports:
      - 8080:5173
    working_dir: /app
    volumes:
      - ./app/public:/app
      - ./app:/app
      - /app/node_modules

  pocketbase:
    build:
      context: ./pocketbase
    restart: unless-stopped
    env_file:
      - ./.env.local
    ports:
      - 8090:8090
    volumes:
      - ./pocketbase/pb_hooks:/app/pb_hooks
      - ./pocketbase/pb_data:/app/pb_data
      - ./pocketbase/pb_public:/app/pb_public #optional