services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
      target: deploy
    restart: always
    container_name: money-manager-svelte
    env_file:
      - ./.env
    networks:
      - nginx

  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile.prod
    restart: always
    env_file:
      - ./.env
    ports:
      - 8090:8090
    volumes:
      - ./pocketbase/pb_hooks:/app/pb_hooks
      - ./pocketbase/pb_data:/app/pb_data
      - ./pocketbase/pb_public:/app/pb_public
    networks:
      - nginx

networks:
  nginx:
    name: nginx
    external: true

