services:
  app:
    build:
      context: app
      target: deploy
    env_file:
      - ./.env
    ports:
      - 8080:80

  api:
    build:
      context: ./api
      target: dev
    env_file:
      - ./.env
    ports:
      - 3000:3000
    volumes:
      - ./api:/api